### ISSUE TITLE
Cannot run the code on ATTINY85 8mhz, fatal error: TinywireM.h: No such files in directory.

### ISSUE THREAD

**Issue by ArtofWar-dev** [adafruit/Adafruit_VCNL4010#5]
Hi I use the example code for this on the Arduino Uno, and it works fine. When I try to upload the code on my Bootloaded ATTINY85 im getting the error, i know the AdaFruit_VCNL4010 is compatible with ATTINY85. Please Help

**Error im getting:**
fatal error: TinywireM.h: No such files in directory.
#include<TinyWireM.h>

**The code i use**
#include <Wire.h>
#include "Adafruit_VCNL4010.h"

Adafruit_VCNL4010 vcnl;

#if defined(ARDUINO_ARCH_SAMD)
// for Zero, output on USB Serial console, remove line below if using programming port to program the Zero!
   #define Serial SerialUSB
#endif

void setup() {
  Serial.begin(9600);
  Serial.println("VCNL4010 test");

  if (! vcnl.begin()){
    Serial.println("Sensor not found :(");
    while (1);
  }
  Serial.println("Found VCNL4010");
}

void loop() {
   Serial.print("Ambient: "); Serial.println(vcnl.readAmbient());
   Serial.print("Proximity: "); Serial.println(vcnl.readProximity());
   delay(100);
}

**Comment by ladyada** [comment]
sorry for delay on getting to this issue - we don't use TinyWireM anymore for trinket/gemma with attiny85, we have Wire compatibility so try the latest version of this library!
