### ISSUE TITLE
Library keeps hanging in read8

### ISSUE THREAD

**Issue by clankill3r** [adafruit/Adafruit_VCNL4010#6]
When I put a motorshield on the arduino the code for the proximity sensor hangs.
I added some println's, "A", "B", "C", "D" etc.
I will print A, B and C but never reaches D.
So somewhere inside `uint8_t rev = read8(VCNL4010_PRODUCTID);` it hangs.

(On !Wire.available() eventaully...).

```
boolean Adafruit_VCNL4010::begin(uint8_t addr) {
   Serial.print("A");
  _i2caddr = addr;
  Serial.print("B");
  Wire.begin();
  Serial.print("C");

  **uint8_t rev = read8(VCNL4010_PRODUCTID);**
  Serial.print("D");
  //Serial.println(rev, HEX);
  if ((rev & 0xF0) != 0x20) {
  	Serial.print("E");
    return false;
  }
	
  Serial.print("F");  
  setLEDcurrent(20);
  Serial.print("G");
  setFrequency(VCNL4010_390K625);
  Serial.print("H");

  write8(VCNL4010_INTCONTROL, 0x08);
  Serial.print("I");
  return true;
}
```

**Comment by ladyada** [comment]
sorry for delay on getting to this issue - is this still an issue? it sounds like a wiring problem. will close since its been a while, re-open if you're still getting failures!
